import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../services/api_service.dart';

class ClientReceivablesScreen extends StatefulWidget{const ClientReceivablesScreen({super.key,required this.session});final AuthSession session;@override State<ClientReceivablesScreen> createState()=>_State();}
class _State extends State<ClientReceivablesScreen>{final db=Supabase.instance.client;bool loading=true;String? error;List<dynamic> clients=[],invoices=[];
@override void initState(){super.initState();load();}
Future<void> load()async{setState((){loading=true;error=null;});try{final r=await Future.wait([db.from('clients').select().order('name'),db.from('client_invoices').select('*, clients(name), projects(name,code)').order('invoice_date',ascending:false)]);if(!mounted)return;setState((){clients=r[0]as List;invoices=r[1]as List;});}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;String money(dynamic v)=>'PKR ${n(v).toStringAsFixed(0)}';
Future<void> receive(Map<String,dynamic> inv)async{final outstanding=(n(inv['total_amount'])-n(inv['paid_amount'])).clamp(0,double.infinity);final c=TextEditingController(text:outstanding.toStringAsFixed(0));final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:Text('Receive ${inv['invoice_number']}'),content:TextField(controller:c,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'Amount',helperText:'Outstanding ${money(outstanding)}')),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Receive'))]));if(ok!=true)return;final amount=n(c.text);if(amount<=0||amount>outstanding)return;final paid=n(inv['paid_amount'])+amount;await db.from('client_invoices').update({'paid_amount':paid,'status':paid>=n(inv['total_amount'])?'paid':'partial'}).eq('id',inv['id']);await load();}
@override Widget build(BuildContext context){final billed=invoices.fold<double>(0,(s,e)=>s+n((e as Map)['total_amount']));final paid=invoices.fold<double>(0,(s,e)=>s+n((e as Map)['paid_amount']));final overdue=invoices.where((e){final m=e as Map;final d=DateTime.tryParse('${m['due_date']}');return d!=null&&d.isBefore(DateTime.now())&&n(m['paid_amount'])<n(m['total_amount']);}).length;return Scaffold(appBar:AppBar(title:const Text('Client Billing & Receivables'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):ListView(padding:const EdgeInsets.all(18),children:[Wrap(spacing:10,runSpacing:10,children:[_Stat('Clients','${clients.length}'),_Stat('Total Billed',money(billed)),_Stat('Received',money(paid)),_Stat('Outstanding',money(billed-paid)),_Stat('Overdue','$overdue')]),const SizedBox(height:18),Text('Invoices',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),if(invoices.isEmpty)const Card(child:ListTile(title:Text('No invoices yet'))),...invoices.map((e){final m=Map<String,dynamic>.from(e as Map);final client=m['clients']is Map?m['clients']as Map:<String,dynamic>{};final project=m['projects']is Map?m['projects']as Map:<String,dynamic>{};final out=(n(m['total_amount'])-n(m['paid_amount'])).clamp(0,double.infinity);final due=DateTime.tryParse('${m['due_date']}');final isOverdue=due!=null&&due.isBefore(DateTime.now())&&out>0;return Card(child:ListTile(onTap:out>0?()=>receive(m):null,leading:Icon(isOverdue?Icons.warning_amber_outlined:Icons.request_quote_outlined),title:Text('${m['invoice_number']} • ${client['name']??'Client'}'),subtitle:Text('${project['code']??''} ${project['name']??''}\nDue ${m['due_date']??'-'} • ${m['status']??'draft'}'),isThreeLine:true,trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text(money(m['total_amount']),style:const TextStyle(fontWeight:FontWeight.bold)),Text('Due ${money(out)}',style:Theme.of(context).textTheme.bodySmall)])));}),const SizedBox(height:60)]));}}
class _Stat extends StatelessWidget{const _Stat(this.label,this.value);final String label,value;@override Widget build(BuildContext context)=>Container(width:180,padding:const EdgeInsets.all(14),decoration:BoxDecoration(border:Border.all(color:Theme.of(context).dividerColor),borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(fontWeight:FontWeight.bold)),Text(label,style:Theme.of(context).textTheme.bodySmall)]));}
