import 'package:flutter/material.dart';
import '../services/api_service.dart';
import 'boq_management_screen.dart';
import 'client_receivables_screen.dart';
import 'material_stock_screen.dart';
import 'operations_create_forms.dart';
import 'project_financial_screen.dart';
import 'supplier_purchase_screen.dart';
class CommercialDashboard extends StatefulWidget{const CommercialDashboard({super.key,required this.session});final AuthSession session;@override State<CommercialDashboard> createState()=>_State();}
class _State extends State<CommercialDashboard>{final api=ApiService();bool loading=true;String? error;int suppliers=0,materials=0,lowStock=0,purchaseOrders=0,expenses=0,invoices=0;@override void initState(){super.initState();load();}Future<void> load()async{setState((){loading=true;error=null;});try{final r=await Future.wait([api.suppliers(widget.session.token),api.materials(widget.session.token),api.lowStockMaterials(widget.session.token),api.purchaseOrders(widget.session.token),api.expenses(widget.session.token),api.invoices(widget.session.token)]);if(!mounted)return;setState((){suppliers=r[0].length;materials=r[1].length;lowStock=r[2].length;purchaseOrders=r[3].length;expenses=r[4].length;invoices=r[5].length;});}catch(e){if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>loading=false);}}Future<void> open(String type)async{final changed=await Navigator.of(context).push<bool>(MaterialPageRoute(builder:(_)=>OperationsCreateScreen(session:widget.session,type:type)));if(changed==true)load();}void push(Widget s)=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>s));
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Commercial Control Center'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(20),children:[Text('Procurement & Finance',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Track suppliers, material stock, purchasing, project costs and billing.'),if(error!=null)...[const SizedBox(height:12),Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))],const SizedBox(height:20),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.25,children:[_Metric(Icons.storefront_outlined,'Suppliers',suppliers),_Metric(Icons.inventory_2_outlined,'Materials',materials),_Metric(Icons.warning_amber_outlined,'Low Stock',lowStock),_Metric(Icons.receipt_long_outlined,'Purchase Orders',purchaseOrders),_Metric(Icons.money_off_outlined,'Expenses',expenses),_Metric(Icons.request_quote_outlined,'Invoices',invoices)]),const SizedBox(height:20),
_Action(Icons.account_balance_wallet_outlined,'Client Billing & Receivables','Invoices, collections, outstanding and overdue balances',()=>push(ClientReceivablesScreen(session:widget.session))),_Action(Icons.local_shipping_outlined,'Supplier & Purchase Control','POs, deliveries, supplier payments and purchase history',()=>push(SupplierPurchaseScreen(session:widget.session))),_Action(Icons.inventory_outlined,'Material Inventory & Stock','Receive, issue, adjust and track project-wise stock',()=>push(MaterialStockScreen(session:widget.session))),_Action(Icons.storefront_outlined,'Add Supplier','Register a supplier or vendor',()=>open('Supplier')),_Action(Icons.inventory_2_outlined,'Add Material','Create stock item and reorder level',()=>open('Material')),_Action(Icons.shopping_cart_checkout_outlined,'Create Purchase Order','Create supplier purchase order',()=>open('Purchase Order')),_Action(Icons.payments_outlined,'Record Project Expense','Labour, material, fuel and site expense',()=>open('Expense')),_Action(Icons.request_quote_outlined,'Create Client Invoice','Billing and receivables',()=>open('Invoice')),_Action(Icons.calculate_outlined,'BOQ Management','Quantities, unit rates, executed work and remaining value',()=>push(BoqManagementScreen(session:widget.session))),_Action(Icons.trending_up_outlined,'Project Financial Control','Contract value, cost, billing, collections and estimated profit',()=>push(ProjectFinancialScreen(session:widget.session)))])));
}
class _Metric extends StatelessWidget{const _Metric(this.icon,this.label,this.value);final IconData icon;final String label;final int value;@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon),const Spacer(),Text('$value',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),Text(label)])));}
class _Action extends StatelessWidget{const _Action(this.icon,this.title,this.subtitle,this.tap);final IconData icon;final String title,subtitle;final VoidCallback tap;@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(icon),title:Text(title),subtitle:Text(subtitle),trailing:const Icon(Icons.chevron_right),onTap:tap));}
