import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../services/api_service.dart';

class ExecutiveDashboard extends StatefulWidget{const ExecutiveDashboard({super.key,required this.session});final AuthSession session;@override State<ExecutiveDashboard> createState()=>_State();}
class _State extends State<ExecutiveDashboard>{final api=ApiService();final db=Supabase.instance.client;bool loading=true;String? error;Map<String,dynamic> k={};List<dynamic> projects=[],invoices=[],materials=[],expenses=[],incidents=[];
@override void initState(){super.initState();load();}
Future<void> load()async{setState((){loading=true;error=null;});try{final r=await Future.wait([api.dashboardKpis(widget.session.token),api.projects(widget.session.token),api.invoices(widget.session.token),api.materials(widget.session.token),api.expenses(widget.session.token),api.safetyIncidents(widget.session.token)]);if(!mounted)return;setState((){k=r[0]as Map<String,dynamic>;projects=r[1]as List;invoices=r[2]as List;materials=r[3]as List;expenses=r[4]as List;incidents=r[5]as List;});}catch(e){if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>loading=false);}}
double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;String money(double v)=>'PKR ${v.toStringAsFixed(0)}';
@override Widget build(BuildContext context){final billed=invoices.fold<double>(0,(s,e)=>s+n((e as Map)['total_amount']));final received=invoices.fold<double>(0,(s,e)=>s+n((e as Map)['paid_amount']));final spent=expenses.fold<double>(0,(s,e)=>s+n((e as Map)['amount']));final low=materials.where((e){final m=e as Map;return n(m['quantity_on_hand'])<=n(m['reorder_level']);}).length;final active=projects.where((e)=>'${(e as Map)['status']}'.toLowerCase()=='active').length;final openSafety=incidents.where((e)=>!['closed','resolved'].contains('${(e as Map)['status']}'.toLowerCase())).length;return Scaffold(appBar:AppBar(title:const Text('Executive Business Dashboard'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(18),children:[Text('Choudhary & Sons',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const Text('Company-wide operational and financial snapshot'),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[_Card(Icons.engineering_outlined,'Active Projects','$active'),_Card(Icons.request_quote_outlined,'Total Billed',money(billed)),_Card(Icons.savings_outlined,'Collections',money(received)),_Card(Icons.schedule_outlined,'Receivables',money(billed-received)),_Card(Icons.payments_outlined,'Recorded Expenses',money(spent)),_Card(Icons.inventory_2_outlined,'Low Stock','$low'),_Card(Icons.health_and_safety_outlined,'Open Safety','$openSafety'),_Card(Icons.people_outline,'Employees','${k['active_employees']??k['employees']??0}')]),const SizedBox(height:22),Text('Project Portfolio',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),...projects.take(8).map((e){final m=e as Map;return Card(child:ListTile(leading:const Icon(Icons.apartment_outlined),title:Text('${m['name']??'Project'}'),subtitle:Text('${m['code']??''} • ${m['status']??'planned'}'),trailing:Text(money(n(m['contract_value'])),style:const TextStyle(fontWeight:FontWeight.bold))));}),const SizedBox(height:18),Text('Attention Required',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),_Alert(Icons.account_balance_wallet_outlined,'Outstanding client receivables',money(billed-received)),_Alert(Icons.inventory_outlined,'Materials at/below reorder level','$low items'),_Alert(Icons.health_and_safety_outlined,'Open safety incidents','$openSafety incidents'),const SizedBox(height:40)])));}}
class _Card extends StatelessWidget{const _Card(this.icon,this.label,this.value);final IconData icon;final String label,value;@override Widget build(BuildContext c)=>Container(width:190,padding:const EdgeInsets.all(16),decoration:BoxDecoration(border:Border.all(color:Theme.of(c).dividerColor),borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon),const SizedBox(height:14),Text(value,style:Theme.of(c).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),Text(label,style:Theme.of(c).textTheme.bodySmall)]));}
class _Alert extends StatelessWidget{const _Alert(this.icon,this.title,this.value);final IconData icon;final String title,value;@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(icon),title:Text(title),trailing:Text(value,style:const TextStyle(fontWeight:FontWeight.bold))));}
