import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../services/api_service.dart';

class SupplierPurchaseScreen extends StatefulWidget { const SupplierPurchaseScreen({super.key,required this.session}); final AuthSession session; @override State<SupplierPurchaseScreen> createState()=>_State(); }
class _State extends State<SupplierPurchaseScreen>{final _api=ApiService();final _db=Supabase.instance.client;bool loading=true;String? error;List<dynamic> suppliers=[],orders=[],deliveries=[],payments=[];
@override void initState(){super.initState();load();}
Future<void> load()async{setState((){loading=true;error=null;});try{final r=await Future.wait([_api.suppliers(widget.session.token),_api.purchaseOrders(widget.session.token),_db.from('purchase_deliveries').select('*, purchase_orders(po_number), materials(name,unit)').order('created_at',ascending:false).limit(100),_db.from('supplier_payments').select('*, suppliers(name), purchase_orders(po_number)').order('created_at',ascending:false).limit(100)]);if(!mounted)return;setState((){suppliers=r[0]as List;orders=r[1]as List;deliveries=r[2]as List;payments=r[3]as List;});}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
double numv(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;String money(dynamic v)=>'PKR ${numv(v).toStringAsFixed(0)}';
Future<void> payment()async{if(suppliers.isEmpty)return;int sid=(suppliers.first as Map)['id']as int;int? po;final amount=TextEditingController(),method=TextEditingController(),ref=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setL)=>AlertDialog(title:const Text('Record Supplier Payment'),content:SizedBox(width:440,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<int>(value:sid,decoration:const InputDecoration(labelText:'Supplier'),items:suppliers.map((e){final m=e as Map;return DropdownMenuItem(value:m['id']as int,child:Text('${m['name']}'));}).toList(),onChanged:(v)=>setL(()=>sid=v!)),const SizedBox(height:10),DropdownButtonFormField<int?>(value:po,decoration:const InputDecoration(labelText:'Purchase Order (optional)'),items:[const DropdownMenuItem<int?>(value:null,child:Text('General payment')), ...orders.map((e){final m=e as Map;return DropdownMenuItem<int?>(value:m['id']as int,child:Text('${m['po_number']}'));})],onChanged:(v)=>setL(()=>po=v)),const SizedBox(height:10),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount')),const SizedBox(height:10),TextField(controller:method,decoration:const InputDecoration(labelText:'Payment method')),const SizedBox(height:10),TextField(controller:ref,decoration:const InputDecoration(labelText:'Reference'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))])));if(ok!=true||numv(amount.text)<=0)return;await _db.from('supplier_payments').insert({'supplier_id':sid,'purchase_order_id':po,'amount':numv(amount.text),'payment_method':method.text.trim(),'reference':ref.text.trim()});await load();}
@override Widget build(BuildContext context){final poTotal=orders.fold<double>(0,(s,e)=>s+numv((e as Map)['total_amount']));final paid=payments.fold<double>(0,(s,e)=>s+numv((e as Map)['amount']));return Scaffold(appBar:AppBar(title:const Text('Supplier & Purchase Control'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:payment,icon:const Icon(Icons.payments_outlined),label:const Text('Supplier Payment')),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):ListView(padding:const EdgeInsets.all(18),children:[Wrap(spacing:10,runSpacing:10,children:[_Stat('Suppliers','${suppliers.length}'),_Stat('Purchase Orders','${orders.length}'),_Stat('PO Value',money(poTotal)),_Stat('Payments',money(paid))]),const SizedBox(height:18),Text('Purchase Orders',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),...orders.map((e){final m=e as Map;return Card(child:ListTile(leading:const Icon(Icons.receipt_long_outlined),title:Text('${m['po_number'] ?? 'PO'}'),subtitle:Text('${m['status'] ?? 'draft'} • Expected ${m['expected_date'] ?? '-'}'),trailing:Text(money(m['total_amount']),style:const TextStyle(fontWeight:FontWeight.bold))));}),const SizedBox(height:18),Text('Recent Deliveries',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),if(deliveries.isEmpty)const Card(child:ListTile(title:Text('No deliveries recorded yet'))),...deliveries.take(20).map((e){final m=e as Map;final mat=m['materials']is Map?m['materials']as Map:<String,dynamic>{};final po=m['purchase_orders']is Map?m['purchase_orders']as Map:<String,dynamic>{};return Card(child:ListTile(leading:const Icon(Icons.local_shipping_outlined),title:Text('${mat['name'] ?? 'Material'} • ${m['quantity']} ${mat['unit'] ?? ''}'),subtitle:Text('${po['po_number'] ?? ''} • ${m['delivery_date']} • Challan ${m['challan_number'] ?? '-'}')));}),const SizedBox(height:18),Text('Supplier Payments',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),if(payments.isEmpty)const Card(child:ListTile(title:Text('No supplier payments recorded'))),...payments.take(20).map((e){final m=e as Map;final s=m['suppliers']is Map?m['suppliers']as Map:<String,dynamic>{};return Card(child:ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:Text('${s['name'] ?? 'Supplier'}'),subtitle:Text('${m['payment_date']} • ${m['payment_method'] ?? ''} • ${m['reference'] ?? ''}'),trailing:Text(money(m['amount']),style:const TextStyle(fontWeight:FontWeight.bold))));}),const SizedBox(height:80)]));}}
class _Stat extends StatelessWidget{const _Stat(this.label,this.value);final String label,value;@override Widget build(BuildContext context)=>Container(width:180,padding:const EdgeInsets.all(14),decoration:BoxDecoration(border:Border.all(color:Theme.of(context).dividerColor),borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(fontWeight:FontWeight.bold)),Text(label,style:Theme.of(context).textTheme.bodySmall)]));}
